[package]
name = "grep-rs"
description = "A simple grep implementation in Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
regex = "1.10.4"
